baseURL: ''
languageCode: 'en-us'
title: 'My New Hugo Site'
theme: 'PaperMod'

params:
  cover:
    linkFullImages: true

  showBreadCrumbs: true
  showReadingTime: true
  showPostNavLinks: true
  showShareButtons: false

taxonomies:
  tag: "tags"
  category: "categories"
  project: "projects"

menu:
  main:
    - identifier: quotes
      name: Quotes
      url: /quotes/
      weight: 0
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
      